---
title: "Course Description"
editor: visual
---

This is a survey course in comparative political economy, a field of
inquiry within the subfield of comparative politics that explores the
interaction of politics and the economy. Comparative political economy
is one of the most active research fields in comparative politics and is
comprised of a wide range of research topics. Frequently the focus of
research in comparative political economy is on how institutions
influence economic outcomes. How, for example, do property rights
facilitate investment and economic growth? How do different colonial
legacies inhibit or promote economic performance? Sometimes, however,
institutions become the dependent variable in our analysis. How does
wealth influence regime stability? Or how does economic globalization
affect welfare states? This course will address questions like these
through an exploration of relevant literature. The syllabus emphasizes
current research agendas in political economy, and its main goal is to
provide students with a broad overview of contemporary debates in the
field.
