---
title: "Syllabus"
editor: visual
---

## Course information

| Course: PSC 2339-Comparative Political Economy
| Lecture: TR 12:45-2:00
| Classroom: 1776 G ST NW, Rm C-119

## Prerequisites

Students are required to take *PSC 1001-Introduction to Comparative
Politics* before enrolling in this course.

## Learning objectives

Students in this course should strive to meet the following objectives:

1.  Demonstrate a basic familiarity with the field of comparative
    political economy.
2.  Leverage differences between countries or regions to analyze the
    effects of institutions on economic outcomes and vice-versa.
3.  Demonstrate how historical legacies shape contemporary political and
    economic outcomes.
4.  Discern basic differences in institutional and economic structures
    shape how countries interact with the global economy.

Discern basic differences in institutional and economic structures shape
how countries interact with the global economy.

## Readings

Students will read approximately 75 pages per week of academic material
during the semester.

All academic readings are available through Gelman library proxy
services except the following two texts, which students should purchase
the following two texts from an online vendor:

📖 Joseph Stiglitz, *People, Power, and Profits*

📖 John Judis, *The Politics of Our Time*

## Dataquest

Students will be required to complete a series of modules on
[Dataquest.io](https://www.dataquest.io/). These will not be graded but
will serve as the basis for a series of data assignments. More
information on accessing Dataquest will be provided in class.

## Class participation

This class is structured so that students have ample opportunity to
participate in class discussions. Students are encouraged to voice their
opinions both in small group settings as well as in broader class
discussions and to ask clarifying questions when the need arises.

## Assignments

1.  Three data assignments (5% percent each)
2.  Three exams (15% each)
3.  Final project (40% of final grade)
    a.  Outline and sources (10%)
    b.  White paper (10%)
    c.  Power BI report (20%)

### Data assignments

Students will complete three graded data assignments that will be based
on the Dataquest modules covered in class. These exercises will be
oriented towards strengthening the student's ability to manipulate,
visualize and communicate data with Microsoft Excel and Power BI.

### Exams

Students will take three non-comprehensive takehome exams. These exams
will test the students' knowledge of the reading material as well as
arguments, concepts, and facts presented and discussed in class. Exams
will be comprised some combination of multiple choice, fill in the
blank, true or false, short answer and essay questions.

### Final project

Each student will complete a final project that will be developed
throughout the semester. The project is comprised of three components
(an outline, a white paper and a Power BI report). The objective of this
project is to develop the student's ability to incorporate data into an
analysis of an important research topic in the field of comparative
politics.

## Out of class preparation

In a 15-week semester, including exam week, students are expected to
spend a minimum of 100 minutes of out-of-class work for every 50 minutes
of direct instruction, for a minimum total of 2.5 hours a week. A
3-credit course should include 2.5 hours of direct instruction and a
minimum of 5 hours of independent learning or 7.5 hours per week.

## Course policies

### Due dates and late assignments

Readings should be completed and videos watched for the day they are
assigned. **With the exception of the third component of the final
project, assignments are due the Sunday after they are assigned. The
third component of the final project is due at 11:59 p.m. on the date of
the scheduled final.** (Note that this does not mean that there is final
exam for this course. This is just the due date for the Power BI
assignment). The official due dates are posted in the "weekly materials"
page for the week that they are due.

Late assignments will be accepted **with a standard penalty of three
percentage points per day** that they are turned in after the official
due date. No exceptions will be made to this policy.

If you are having a personal or medical emergency and are wondering what
to do, start by referencing [this
FAQ](https://studentlife.gwu.edu/student-support-faqs) published by [GW
Student Life](https://studentlife.gwu.edu/). Or just reach out to the
CARE Team at [gwcares\@gwu.edu](mailto:gwcares@gwu.edu). For further
information about different types of support available to you, see the
[course support](\course-support.qmd) page.

While I will always try to be a source of support to my students, please
note that for privacy reasons, the Provost has asked that faculty do not
attempt to verify personal or medical emergencies themselves.

### Make-ups

There are no makeups. Please see the late assignments policy above.

### Attendance

This is an in-person class and you are expected to attend. While there
is no formal attendance requirement, it is a proven fact that students
who attend class tend to perform better on exams and assignments. Also,
the instructor will not provide "makeup sessions" to go over material
that was missed due to absence.

### Grading scale

| Range  | Letter Grade |
|:------:|:------------:|
| 94-100 |      A       |
| 90-93  |      A-      |
| 87-89  |      B+      |
| 84-86  |      B       |
| 80-83  |      B-      |
| 77-79  |      C+      |
| 74-76  |      C       |
| 70-73  |      C-      |
| 67-69  |      D+      |
| 64-66  |      D       |
| 60-63  |      D-      |
|  \<59  |      F       |

### Class recordings

All classes will be recorded. Recordings will be posted on the course
Blackboard site.

### Lateness

Please come to class on time. It is distracting to me and to other
students when you enter the room late.

### Laptops and cell phones

Please put away your cell phones during class. It is fine to use
computers to take notes, but you should refrain from checking social
media and email.

### Diversity in the classroom

We want to make sure that everyone has an opportunity to participate in
class and to get the most out of their learning experience at GW.
Moreover, we all benefit from a diversity of views in the classroom.
Therefore, please be respectful of other people's views and be mindful
of when others are trying to participate.

### Learning Needs

Please let me know if you have any special needs or learning
requirements and so that I can accommodate them.

### Email

I try to respond to emails within 24 hours except on weekends. It is
usually preferred to talk to me in person, however, either after class
or during office hours.

### Food

Students are permitted to eat light snacks, but please refrain from
bringing sugary drinks, coffee or large, odiferous meals.

## University policies

### Academic integrity

By taking this course, you are agreeing to abide by the [GWU code of
Academic
Integrity](http://studentconduct.gwu.edu/code-academic-integrity).
According to this code, academic dishonesty is defined as "cheating of
any kind, including misrepresenting one's own work, taking credit for
the work of others without crediting them and without appropriate
authorization, and the fabrication of information." Note that this is
not a comprehensive list. Other types of academic dishonesty include
providing false or misleading information in an effort to postpone an
exam or to get an extension on an assignment and providing substantially
similar material for a writing assignment for assignments in two
different courses without the prior permission of the faculty members
teaching those courses. The minimum penalty for academic dishonesty is a
failing grade on the assignment in question and the maximum penalty is
failure of the class. Furthermore, the violation will be reported to
GW's Office of Academic Integrity, which can impose additional penalties
beyond those I may impose.

### Religious holidays

Students must notify faculty during the first week of the semester in
which they are enrolled in the course, or as early as possible, but no
later than three weeks prior to the absence, of their intention to be
absent from class on their day(s) of religious observance. If the
holiday falls within the first three weeks of class, the student must
inform faculty in the first week of the semester. For details and
policy, see ["Religious
Holidays."](https://provost.gwu.edu/policies-procedures-and-guidelines.)

### Use of electronic materials and class recordings

Students are encouraged to use electronic course materials, including
recorded class sessions, for private personal use in connection with
their academic program of study. Electronic course materials and
recorded class sessions should not be shared or used for non-course
related purposes unless express permission has been granted by the
instructor. Students who impermissibly share any electronic course
materials are subject to discipline under the Student Code of Conduct.
Please contact the instructor if you have questions regarding what
constitutes permissible or impermissible use of electronic course
materials and/or recorded class sessions. Please contact [Disability
Support Services](https://disabilitysupport.gwu.edu) if you have
questions or need assistance in accessing electronic course materials.
