---
title: "Course Schedule"
tbl-colwidths: [5,15,30,5,5,5,25,5,5]
editor: visual
---

```{r setup, include = FALSE}
library(lubridate)

mon <- as_date("2022-08-29")
tues <- mon+days(1)
wed <- mon+days(2)
thur <- mon+days(3)
fri <- mon+days(4)

advdate <- function(day, week) {
  date <- (day + weeks(week))
  dm <- paste(month(date, label = TRUE)," ",day(date))
  return(dm)  
} 
```

This page displays an outline of the topics, content, and assignments
for the semester. Slides and assignment links will go live as the
semester progresses.

::: column-screen-inset-right
|           Week            | Date                 | Topic                                 |                                                                              Reading                                                                              |                                    Video                                    |                         Slides                         | Skill                                    |                                                                    Dataquest                                                                     |                                                                                               Assignment                                                                                               |
|:------:|--------|--------|:------:|:------:|:------:|--------|:------:|:------:|
|  [1](/weeks/week-1.html)  | `r advdate(tues,0)`  | Course overview                       |                                                                                                                                                                   |                                                                             |                                                        | Explore MS 365 & Dataquest               |                                                                                                                                                  |                                                                                                                                                                                                        |
|                           | `r advdate(thur,0)`  | The economy and society               |                                        [ðŸ“–](https://ebookcentral.proquest.com/lib/gwu/reader.action?docID=3117969&ppg=178)                                        |                                                                             |    [ðŸ–¥ï¸](/slides/lecture-1.html "Lecture 1 slides")     | Understanding data                       |                           [ðŸ“‰](https://app.dataquest.io/c/141/m/756/defining-data/1/introduction-to-data-foundations)                            |                                                                                                                                                                                                        |
|  [2](/weeks/week-2.html)  | `r advdate(tues,1)`  | Institutions and development          |                                        [ðŸ“–](https://link-springer-com.proxygw.wrlc.org/article/10.1007/s11127-019-00645-z)                                        |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-2.1.html "Lecture 2.1 slides")   | Using data                               |                                   [ðŸ“‰](https://app.dataquest.io/c/141/m/757/how-to-use-data/1/how-to-use-data)                                   |                                                                                                                                                                                                        |
|                           | `r advdate(thur,1)`  | Modernization theory                  | [ðŸ“–](https://blackboard.gwu.edu/webapps/blackboard/execute/content/file?cmd=view&mode=designer&content_id=_12520836_1&course_id=_374099_1 "Cheibub and Vreeland") |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-2.2.html "Lecture 2.2 slides")   | Analyzing data                           |                         [ðŸ“‰](https://app.dataquest.io/c/141/m/758/the-data-analysis-process/1/the-data-analysis-process)                         |                                                                                                                                                                                                        |
|  [3](/weeks/week-3.html)  | `r advdate(tues,2)`  | Democratic backsliding                |                                               [ðŸ“–](https://doi.org/10.1017/S1537592718003377 "Kaufman and Haggard")                                               | [ðŸ“º](https://www.youtube.com/watch?v=jSl9rydcd7k "Data Assignment 1 Video") |  [ðŸ–¥ï¸](/slides/lecture-3.1.html "Lecture 3.1 slides")   | Importing data                           |                    [ðŸ“‰](https://app.dataquest.io/c/127/m/652/importing-data-into-excel-spreadsheets/1/welcome-to-the-course)                     |                                                                                                                                                                                                        |
|                           | `r advdate(thur,2)`  | The resource curse                    |                                                 [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctt7s3wz.10)                                                 |              [ðŸ“º](https://www.youtube.com/watch?v=y7ESq_O3Odw)              |  [ðŸ–¥ï¸](/slides/lecture-3.2.html "Lecture 3.2 slides")   | Organizing data                          |                                    [ðŸ“‰](https://app.dataquest.io/c/127/m/653/organizing-data/1/introduction)                                     |                                                                     [ðŸ§®](/assignments/data-assignment-1.html "Data Assignment 1")                                                                      |
|  [4](/weeks/week-4.html)  | `r advdate(tues,3)`  | Women's empowerment                   |                                             [ðŸ“–](https://www.econstor.eu/bitstream/10419/216551/1/cesifo1_wp8155.pdf)                                             |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-4.1.html "Lecture 4.1 slides")   |                                          |                                                                                                                                                  |                                                                                                                                                                                                        |
|                           | `r advdate(thur,3)`  | Exam 1 review                         |                                                                                                                                                                   |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-4.2.html "Lecture 4.2 slides")   |                                          |                                                                                                                                                  |                           [ðŸ“˜](https://blackboard.gwu.edu/webapps/blackboard/content/listContentEditable.jsp?content_id=_12520539_1&course_id=_374099_1&mode=reset "Exam 1")                           |
|  [5](/weeks/week-5.html)  | `r advdate(tues,4)`  | Programmatic politics vs. clientelism |    [ðŸ“–](https://blackboard.gwu.edu/webapps/blackboard/execute/content/file?cmd=view&mode=designer&content_id=_12522450_1&course_id=_374099_1 "Stokes et. al.")    |                                                                             | [ðŸ–¥ï¸](/slides/lecture-5.1.html "Distributive politics") | Cleaning data I                          |                                 [ðŸ“‰](https://app.dataquest.io/c/127/m/654/cleaning-data---part-i/1/introduction)                                 |                                                                                                                                                                                                        |
|                           | `r advdate(thur,4)`  | Vote buying                           |                                        [ðŸ“–](https://ebookcentral.proquest.com/lib/gwu/reader.action?docID=5732981&ppg=112)                                        |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-5.2.html "Lecture 5.2 slides")   | Cleaning data II                         |                                 [ðŸ“‰](https://app.dataquest.io/c/127/m/655/cleaning-data-part-ii/1/introduction)                                  |                                                                                                                                                                                                        |
|  [6](/weeks/week-6.html)  | `r advdate(tues,5)`  | Ethnicity and public goods            |                                                            [ðŸ“–](http://www.jstor.org/stable/25054263)                                                             |  [ðŸ“º](https://www.youtube.com/watch?v=G9vKgrtDZ-w&t=72s "Bar chart video")  |  [ðŸ–¥ï¸](/slides/lecture-6.1.html "Lecture 6.1 slides")   | Bar charts                               |                                 [ðŸ“‰](https://app.dataquest.io/c/127/m/654/cleaning-data---part-i/1/introduction)                                 |                                                                                                                                                                                                        |
|                           | `r advdate(thur,5)`  | Democracy and redistribution          |                                                 [ðŸ“–](https://doi-org.proxygw.wrlc.org/10.1017/S1537592717002122)                                                  | [ðŸ“º](https://www.youtube.com/watch?v=YOpwcihO-iY&t=39s "Line chart video")  |  [ðŸ–¥ï¸](/slides/lecture-6.2.html "Lecture 6.2 slides")   | Line charts                              |                          [ðŸ“‰](https://app.dataquest.io/c/131/m/670/line%2C-scatter%2C-and-combo-charts/1/introduction)                           |                                                                                                                                                                                                        |
|  [7](/weeks/week-7.html)  | `r advdate(tues,6)`  | Washington consensus reforms          |                                    [ðŸ“–](https://www.brookings.edu/wp-content/uploads/2021/02/Washington-Consensus-Reforms.pdf)                                    |   [ðŸ“º](https://www.youtube.com/watch?v=NDszBjbvSFA "Scatter plot video")    |  [ðŸ–¥ï¸](/slides/lecture-7.1.html "Lecture 7.1 slides")   | Scatter plots                            |                          [ðŸ“‰](https://app.dataquest.io/c/131/m/670/line%2C-scatter%2C-and-combo-charts/1/introduction)                           |                                                                                                                                                                                                        |
|                           | `r advdate(thur,6)`  | The gendered legacy of reform         |                                [ðŸ“–](https://eresgw-wrlc-org.proxygw.wrlc.org/x/docs/gelm/teitelbaum_emmanuel/LourdesChapter3.pdf)                                 |      [ðŸ“º](https://www.youtube.com/watch?v=ixjWeXbYVl0 "Mapping video")      |  [ðŸ–¥ï¸](/slides/lecture-7.2.html "Lecture 7.2 slides")   | Maps                                     |                                                                                                                                                  |                                                                     [ðŸ§®](/assignments/data-assignment-2.html "Data assignment 2")                                                                      |
|  [8](/weeks/week-8.html)  | `r advdate(tues,7)`  | Populism and social policy            |                                        [ðŸ“–](https://onlinelibrary-wiley-com.proxygw.wrlc.org/doi/full/10.1111/dech.12578)                                         |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-8.1.html "Lecture 8.1 slides")   |                                          |                                                                                                                                                  |                                                                                                                                                                                                        |
|                           | `r advdate(thur,7)`  | Exam 2 review                         |                                                                                                                                                                   |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-8.2.html "Lecture 8.2 slides")   |                                          |                                                                                                                                                  |                                                                                                   ðŸ“˜                                                                                                   |
|  [9](/weeks/week-9.html)  | `r advdate(tues,8)`  | No class-Fall break                   |                                                                                                                                                                   |                                                                             |                                                        |                                          |                                                                                                                                                  |                                                                                                                                                                                                        |
|                           | `r advdate(thur,8)`  | Final project workshop (virtual)      |                                            [ðŸ“–](https://www.instructionalsolutions.com/blog/how-to-write-white-paper)                                             |                                                                             |                                                        | Writing with Zotero                      |                                                                                                                                                  |                                                                  [âœï¸](/assignments/project-assignment-1.html "Project assignment 1")                                                                   |
| [10](/weeks/week-10.html) | `r advdate(tues,9)`  | Welfare states in the OECD            |            [ðŸ“–](https://blackboard.gwu.edu/webapps/blackboard/execute/content/file?cmd=view&mode=designer&content_id=_12568440_1&course_id=_374099_1)             |          [ðŸ“º](https://www.youtube.com/watch?v=yqAYuAf6zEc&t=175s)           | [ðŸ–¥ï¸](/slides/lecture-10.1.html "Lecture 10.1 slides")  | Wrangling data in the Power Query Editor |               [ðŸ“‰](https://app.dataquest.io/c/120/m/621/get-started-building-with-power-bi/6/building-blocks-of-power-bi-datasets)               |                                                                                                                                                                                                        |
|                           | `r advdate(thur,9)`  | U.S. exceptionalism                   |                                         [ðŸ“–](https://www.brookings.edu/wp-content/uploads/2001/06/2001b_bpea_alesina.pdf)                                         |              [ðŸ“º](https://www.youtube.com/watch?v=VaI3Z4n0QV0)              | [ðŸ–¥ï¸](/slides/lecture-10.2.html "Lecture 10.2 slides")  | Upload data to Power BI                  |                                  [ðŸ“‰](https://app.dataquest.io/c/120/m/622/get-data-in-power-bi/1/introduction)                                  |                                                                                                                                                                                                        |
| [11](/weeks/week-11.html) | `r advdate(tues,10)` | Unions and collective bargaining      |                                       [ðŸ“–](https://journals-sagepub-com.proxygw.wrlc.org/doi/full/10.1177/0143831X18780327)                                       |              [ðŸ“º](https://www.youtube.com/watch?v=hh2MzupXfyQ)              | [ðŸ–¥ï¸](/slides/lecture-11.1.html "Lecture 11.1 slides")  | Create column chart in Power BI          |                [ðŸ“‰](https://app.dataquest.io/c/123/m/627/create-power-bi-visuals/1/introduction-to-working-with-power-bi-visuals)                |                                                                                                                                                                                                        |
|                           | `r advdate(thur,10)` | Varieties of capitalism               |                                                     [ðŸ“–](https://academic.oup.com/book/301/chapter/134893294)                                                     |           [ðŸ“º](https://www.youtube.com/watch?v=IS_SXWXkrVQ&t=28s)           | [ðŸ–¥ï¸](/slides/lecture-11.2.html "Lecture 11.2 slides")  | Create line chart in Power BI            |                                                                        ðŸ“‰                                                                        |                                                                                                                                                                                                        |
| [12](/weeks/week-12.html) | `r advdate(tues,11)` | Globalization                         |                                       [ðŸ“–](https://www.annualreviews.org/doi/full/10.1146/annurev-economics-080315-015041)                                        |              [ðŸ“º](https://www.youtube.com/watch?v=p4pmyTn8tFc)              | [ðŸ–¥ï¸](/slides/lecture-12.1.html "Lecture 12.1 slides")  | Create map in Power BI                   | [ðŸ“‰](https://app.dataquest.io/c/123/m/693/create-a-data-driven-story-with-power-bi-reports-ii/1/introduction-to-interactive-data-visualizations) |                                                                                                                                                                                                        |
|                           | `r advdate(thur,11)` | Inequality                            |                                         [ðŸ“–](https://www.amazon.com/gp/product/B07P92PDLF/ref=dbs_a_def_rwt_bibl_vppi_i2)                                         |              [ðŸ“º](https://www.youtube.com/watch?v=ygEST0CIsl4)              | [ðŸ–¥ï¸](/slides/lecture-12.2.html "Lecture 12.2 slides")  | Create scatter plot in Power BI          |                      [ðŸ“‰](https://app.dataquest.io/c/123/m/629/create-dashboards-in-power-bi/1/introduction-to-dashboards)                       |                                                                                                                                                                                                        |
| [13](/weeks/week-13.html) | `r advdate(tues,12)` | Final project workshop (virtual)      |                                                                                                                                                                   |                                                                             |                                                        |                                          |                                                                                                                                                  |                                                                                [âœï¸](/project/project-assignment-2.html)                                                                                |
|                           | `r advdate(thur,12)` | No class-Thanksgiving break           |                                                                                                                                                                   |                                                                             |                                                        |                                          |                                                                                                                                                  |                                                                                                                                                                                                        |
| [14](/weeks/week-14.html) | `r advdate(tues,13)` | The populist backlash in the West     |                                                 [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctv2dzzqsn)                                                  |                                                                             | [ðŸ–¥ï¸](/slides/lecture-14.1.html "Lecture 14.1 slides")  |                                          |                                                                                                                                                  |                                                                                                                                                                                                        |
|                           | `r advdate(thur,13)` | The rise of nationalism and socialism |                                                 [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctv2dzzqsn)                                                  |                                                                             | [ðŸ–¥ï¸](/slides/lecture-14.2.html "Lecture 14.2 slides")  |                                          |                                                                                                                                                  |                                                                                                                                                                                                        |
| [15](/weeks/week-15.html) | `r advdate(tues,14)` | Climate change and collective action  |                              [ðŸ“–](https://direct.mit.edu/glep/article/20/4/4/95068/Prisoners-of-the-Wrong-Dilemma-Why-Distributive)                               |                                                                             |                           ðŸ–¥ï¸                           |                                          |                                                                                                                                                  |                                                                                                                                                                                                        |
|                           | `r advdate(thur,14)` | Exam 3 review                         |                                                                                                                                                                   |                                                                             |                           ðŸ–¥ï¸                           |                                          |                                                                                                                                                  | [ðŸ“˜](https://blackboard.gwu.edu/webapps/blackboard/content/listContentEditable.jsp?content_id=_12655260_1&course_id=_374099_1 "Exam 3")[âœï¸](/project/project-assignment-3.html "Project assignment 3") |
:::
