---
title: "Lecture 8.1"
subtitle: "Populism and Social Policy"
author: "Emmanuel Teitelbaum"
footer: "[PSC 2339 Website](https://psc2339.com)"
logo: "images/cpe_logo.png"
format:
  revealjs:
    theme: moon
    transition: fade
    slide-number: true
execute:
  echo: false
  freeze: auto
---

# What is Populism?

## Defining Populism

- Way of doing politics
- Four essential characteristics
  - Speaking directly to voters
  - Speaking as outsiders
  - Pitting ordinary people against elites
  - Post-truth rhetoric
  
## Populism vs. Neoliberalism

- Economic views predate neoliberalism
- Focus on domestic rather than international markets
- Attack rights agenda of "mature" neoliberalism
- Attacks on the poor
- Authoritarian tactics

# Causes of Populism

## Increased Inequality

- Within countries
  - Top 1%
  - Privatization
  - Trade liberalization
  - Flexible labor markets
- Between countries
  - Winners and losers
  - EOI vs. ISI 
  - 2008 financial crisis

## Social Policy

- Emphasis on "service provisioning"
  - Instead of welfare states
- Provisioning through private sector 
  - outsourcing
  - NGOs
- Led to enrichment of public servants

## Individual Rights

- New rights granted to women, minorities and the poor
- Done through elite bargains rather than social movements
- Reflected in macro-agendas of International Orgs
  - "Millenium Development Goals" 
  - "Sustainable Development Goals"
- Led to backlash among middle-class voters

# Discussion

## Country Cases

- Philippines
- United States
- Brazil 

- How did populist leaders in these countries harness resentments against women and minorities? 

## How Should International Orgs Respond?

- Should we modify/abandon...
  - Millennium Development Goals
  - Sustainable Development Goals
- Should reforms occur at a different pace?
- Should different economic policies be promoted?
  - Less emphasis on openness? 
  - More emphasis on redistribution? 
  - Other ideas? 


