---
title: "Lecture 12.1"
subtitle: "Globalization"
author: "Emmanuel Teitelbaum"
footer: "[PSC 2339 Website](https://psc2339.com)"
logo: "images/cpe_logo.png"
format:
  revealjs:
    theme: moon
    transition: fade
    slide-number: true
execute:
  echo: false
  freeze: auto
---

## Globalization

- At the broadest level, globalization is the increasing integration of people, cultures and institutions

- IMF's four aspects of globalization: trade; investment; migration; knowledge

- In economics, globalization typically refers to increasing trade and investment

## Benefits of Globalization

- Increased capital flows
- Sharing of knowledge & technology
- Lower prices
- Cultural exchange
- New economic opportunities
- Others? 

## Challenges of Globalization

- Exploitation
- Weak regulation
- High start-up/investment costs
- Localized job loss/displacement
- Immigration
- Others? 

## Theory of Comparative Advantage

- Comparative advantage: the ability of a country to produce something at a lower opportunity cost relative to other countries (Ricardo)

- For example, low-income countries have a comparative advantage in labor-intensive goods, high-income countries have a comparative advantage in high-skill and technology-intensive sectors

- Capital and labor will naturally reallocate based on logic of comparative advantage 

## The China Shock

- Is the theory of comparative advantage true? 

- Will capital and labor reallocate from low-skill to high-skill sectors? 

- Or is localized job loss more enduring?
  
## Autor et. al. 

- How to read an econ paper

- How to read a regression table

- Interpreting results

- What are the main conclusions? Do they ring true to you? 

## Detour

- FRED St. Louis

- [Updated mfg data](https://fred.stlouisfed.org/graph/?g=1Gor) 

## Updating Graphs

- Form new groups

- Select one graph from WB

- Update it

- Discuss: what has changed?

