---
title: "Lecture 1"
subtitle: "Polanyi's Great Transformation"
author: "Emmanuel Teitelbaum"
footer: "[PSC 2339 Website](https://psc2339.com)"
logo: "images/cpe_logo.png"
format:
  revealjs:
    theme: moon
    transition: fade
    slide-number: true
execute:
  echo: false
  freeze: auto
---

# Overview

## Polanyi's Obejctives

-   Explain rise of fascism, political instability and war
-   Advance an argument about negative effects of economic liberalism
-   Provide an alternative vision of the economy's place in society
-   Defend market regulation as not inherently "leftist"

::: notes
Key Arguments Self-regulating market Birth of liberalism Double movement
:::

# The Self-Regulating Market

## The "Invisible Hand"

-   19th century economic liberalism
    -   Ricardo/Smith
-   An economy directed by market prices and nothing but market prices
-   Polanyi calls it a "dangerous fantasy"
-   Tremendous amount of bureaucracy/governance required to maintain
    free markets

## State of Nature I

-   For Smith, our nature is to "truck, barter and trade"
-   For Polanyi, we are communal by nature
-   Markets have always played some role in society but not the dominant
    role
-   Importance of ethnography
    -   Evidence-based approach
    -   Not just a rhetorical device

## State of Nature II

-   Trobriand Islanders (Papua New Guinea)
-   People motivated by status more than money
    -   Money is a means to and end
-   Money not that relevant for distribution
    -   Reciprocity
    -   Redistribution
    -   Householding

## Discussion

-   What is your view of the state of nature?
-   Is it more similar to Karl Polanyi's or Adam Smith's?

# The Birth of Liberalism

## Where Did Liberalism Come From?

-   Does not date back to Smith or Ricardo
-   These thinkers were ahead of their time
-   Emerged out of class politics following industrial revolution

::: notes
Liberalism is a relatively recent ideology/practice
:::

## Elements of Liberalism

-   Unfettered labor market
    -   Cheap labor for industry
-   Gold standard
    -   Facilitated trade
    -   Kept prices in check
-   Free trade
    -   Industrialists/traders wanted to access raw materials
    -   Facilitated by the gold standard

::: notes
Liberalism was dopted to suit needs of industry and instability in the
international economy Needs: price stability, cheap labor, raw materials
:::

## The Gold Standard (1879-1973)

-   Pegging the value of the dollar to gold
-   Problems
    -   Deflationary: could not print money in excess of gold supply
    -   Led to dramatic boom-bust cycles
-   Reforms
    -   1931: Roosevelt ends gold standard domestically
    -   1971: Nixon ends Bretton Woods

::: notes
The gold standard was problematic because it prevented the government
from undertaking monetary policy to counteract economic downturns
:::

## 19th Century Panics

```{r boom-bust}
library(fredr)
library(tidyverse)
library(plotly)
library(scales)
library(ecm)
library(htmlwidgets)

# import data

api_key <- Sys.getenv("FRED_API_KEY") 
fredr_set_key(api_key)
st_date <- as.Date("1857-01-01")
ed_date <- as.Date("1971-12-01")  

recession <- fredr(series_id = "USRECD", observation_start = as.Date(st_date), observation_end = as.Date(ed_date))    

cpr <- fredr(series_id = "M13002US35620M156NNBR", observation_start = as.Date(st_date), observation_end = as.Date(ed_date))
colnames(cpr) <- c("Date", "Indicator", "CPR")
cpr <- subset(cpr, !is.na(CPR), select=c(Date, CPR))

# build recession shading function

add_rec_shade<-function(st_date,ed_date,shade_color="darkgray")
{
  recession$diff<-recession$value-lagpad(recession$value,k=1) #code 1 for 1st day of recession, -1 for first day after recession ends
  recession<-recession[!is.na(recession$diff),] #drop 1st N.A. value
  recession.start<-recession[recession$diff==1,]$date #create vector of recession start dates
  recession.end<-recession[recession$diff==(-1),]$date #create vector of recession end dates
  
  if(length(recession.start)>length(recession.end)) # if there are more dates listed in recession.start than recession.end
  {recession.end<-c(recession.end,Sys.Date())} # enter system date for last date in recession.end
  if(length(recession.end)>length(recession.start)) # if there are more dates listed in recession.end than recession.start         
  {recession.start<-c(min(recession$date),recession.start)} # enter the earliest date in recession$date as first date in recession.start
  
  recs<-as.data.frame(cbind(recession.start,recession.end)) # make a dataframe out of recession.start and recess.end
  recs$recession.start<-as.Date(as.numeric(recs$recession.start),origin=as.Date("1970-01-01")) # set origin date
  recs$recession.end<-as.Date(recs$recession.end,origin=as.Date("1970-01-01")) # set origin date
  if(nrow(recs)>0) # if the number of rows in recs > 0
  {
    rec_shade<-geom_rect(data=recs, inherit.aes=F, #inherit.aes=F overrides default aesthetics
                         aes(xmin=recession.start, xmax=recession.end, ymin=0, ymax=30), 
                         fill=shade_color, alpha=0.5)
    return(rec_shade)
  }
}

# build base plot using ggplot 

theme_set(theme_minimal())

cpr_polanyi <- ggplot(cpr, aes(x=Date, y = CPR)) + 
  geom_line(color = "darkblue") +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  labs(title= "Commercial Paper Rates for New York",  
       x = "", y = "Percent") +
  theme(plot.title = element_text(face="bold")) +
  add_rec_shade()

# build interactive plotly chart    

cpr_polanyi <- ggplotly(cpr_polanyi) %>%
  
  # add source
  layout(annotations = list(text = "Source: NBER, Retrieved from FRED, Federal Reserve Bank of St. Louis.",  
                            font = list(size = 10), showarrow = FALSE,
                            xref = 'paper', x = 1, xanchor = 'right', xshift = 0,
                            yref = 'paper', y = -.1, yanchor = 'auto', yshift = 0)) %>%
  # add web address
  layout(annotations = list(text = "www.psc2339.com", 
                            font = list(size = 10, color = 'grey'), showarrow = FALSE,
                            xref = 'paper', x = .5, xanchor = 'center', xshift = 0,
                            yref = 'paper', y = 1, yanchor = 'top', yshift = 0)) %>%
  # change hoverinfo for recession shading 
  style(hoverinfo="skip", traces = 2)

cpr_polanyi

saveWidget(cpr_polanyi, "cpr_polanyi.html")

```

## Discussion

-   Polanyi argues that economic liberalism generates political
    instability
-   Looking at the graph, do you see the connection?
-   Can you also find evidence challenging Polanyi's view?

# The "Double Movement"

## Small Groups

-   Review the concept of the double movement as it is presented in
    Chapter 11 of *The Great Transformation*
-   What does Polanyi mean by a "movement" and a "counter-movement"?
-   Who are the actors involved?
    -   Who is affected by this "movement"
    -   What does the "counter-movement" entail?

## Description of Double Movement

-   Movement: expansion of liberalism and self-regulating markets
-   Counter-movement: reaction of society against dislocation caused by
    markets
-   New regulations
    -   Purpose is to shelter land, labor and the money supply against
        "devastating effects" of policies used to sustain
        self-regulating markets
    -   Importance of class dynamics: winners and losers

## Who are the Opponents of Liberalism?

-   Not a unified, hegemonic left or an anti-liberal ideology
-   Responses are rather piecemeal
    -   Regulation arises in many areas
    -   Across many countries
    -   In response to similar problems
-   Regulation is a result of liberalism's failure, not its cause

## Small Groups

-   Can Polanyi's theory of the "double movement" be applied to
    contemporary politics?
-   Provide at least two concrete examples to support your view
    -   Be sure to identify
        -   The "movement"
        -   The "countermovement"
        -   The actors involved, e.g. winners and losers
