---
title: "Lecture 14.1"
subtitle: "The Populist Backlash in the West"
author: "Emmanuel Teitelbaum"
footer: "[PSC 2339 Website](https://psc2339.com)"
logo: "images/cpe_logo.png"
format:
  revealjs:
    theme: moon
    transition: fade
    slide-number: true
execute:
  echo: false
  freeze: auto
---

# The Origins of Populism

## What is Populism? {.smaller}

- A political movement that champions the people against the establishment 
- Left-wing populism: dyadic and vertical, mobilized along class lines
	- Government/elites have forgotten about the ordinary people
	- "Ordinary people" could be the middle class or the poor, depending on the country or region
- Right-wing populism: triadic and horizontal, mobilized along class and ethnic lines
	- Government/elites have forgotten about the ordinary people in the racial or ethnic majority 
	- Attacks establishment for siphoning resources to immigrants and minorities
-	Crucially, populists operate inside of a democratic system
	- As opposed to fascists or left-wing extremists in Europe or Latin America

## Where Does Populism Come From? {.smaller}

- Reaction to changes in the economy (and immigration)
- Often spurred by laissez-faire economic policies that benefit the rich
- Frequently the long-term result of economic crisis (1870s-1880s, 1929, late-1970s, 2008, etc.)
	- Populists accuse mainstream parties of ignoring crisis altogether, not addressing the root causes of the crisis, or selling out ordinary voters in order to resolve crisis  
- Most left-wing populist movements demand government intervention that will reduce inequality and restore the middle class
- But populist demands can be coupled with demands to get the government out of the economy
	- Usually a component of right-wing populist groups
	- The government “distorts” the economy by taxing wealth and giving it to poor minorities
	- Or to middle class bureaucrats 

## Neoliberal Policy in the U.S. {.smaller}

- Birthplace of neoliberalism 
	- Home of “Washington Consensus”
- Reaction to competitive challenges faced by U.S. business starting in the 1970s
	- Factories in Western Europe and Japan
	- Steel production throughout Asia
	- Textile production in developing countries
- Business felt regulations and unions prevented them from competing
	- Repressed unions 
	- Moved factories abroad and to “right to work” states
	- Hired more immigrant workers
		- 1965 Immigration and Naturalization Act (Hart-Celler)
		- From quota-based to family and skill-based immigration 
	- Pushed for free trade agreements like NAFTA
- Problem was that immigration and trade were not popular with most voters
	- Created backlash that populists could exploit

# Populism in the United States 

## Populism in the U.S. I {.smaller}

- People’s Party in the U.S. (1890s) 
	- Formed by members of Kansas Farmers’ Alliance and Knights of Labor
	- Reaction to Grover Cleveland and "robber baron" capitalism of 19th century
- Grew out of farm revolt of 1870s and 1880s
	- Steep fall in agricultural prices
	- Aggravated by increased transportation costs 
		- Railroad monopolies
- Saw themselves as representing people vs. elites
	- People = farmers and workers
	- Elites = capitalists, speculators and mainstream parties
- Won lots of seats in 1894 but was coopted by mainstream parties in subsequent years

## Populism in the U.S. II {.smaller}

- Huey Long 
	- Governor of Louisiana (1928-1932); U.S. Senator (1932-35) 
	- Railed against power and influence of oil companies
	- “Share Our Wealth Society”
		- Proposed wealth cap ($5 million per family; $1 million per individual)
		- Use revenue to fund guaranteed income
	- Forced Roosevelt to pass “Second New Deal” that included social security, NLRA, WPA and wealth taxes
	- Assassinated in 1935
- George Wallace 
  - Governor of Alabama (four terms)
  - Government "full of rich people" who wanted to give their money to the poor
  - Led conservative backlash to Civil Rights Act, Voting Rights Act and racial integration 
  - Framed opposition to integration as defense against “big government”



## Populism in the U.S. III {.smaller}

- Reaction to rise of neoliberalism 
- Ross Perot
	- Attacked trade deals and distortion of politics by big business
	- [Ross Perot's Giant Sucking Sound](https://youtu.be/xQ7kn2-GEmM)
- Pat Buchanan 
	- Also attacked trade deals, but also immigration
- Tea Party
	- Attacked Obama’s mortgage bailouts, Obamacare and illegal immigration
- Occupy Wall Street
	- Attacked Obama for not being tough enough on bankers, focused on inequality
	- [The Occupy Movement](https://youtu.be/KFOWci6yrSs)

# Populism in the U.S. Today

## Trump vs. Sanders {.smaller}

- Trump
	- Prior to running in 2016, he was a moderate on social issues (like abortion) and social spending (supported idea of universal health care)
	- Always opposed free trade and immigration
- Sanders
	- Main target is the “billionaire class” (the 1%)
	- Advocates Nordic-style social democracy as an antidote to rising inequality

## Discussion 

- Was Trump's support more due to a reaction to neolibarlism or to immigration? 
- Why was Bernie Sanders, who focused on inequality and the one percent, ultimately less successful than Trump as a presidential candidate?  
- In your discussion, reference the chapter you read from Judis's *The Populist Explosion*

# Project Discussion

## Small Groups (3 or 4 on common topics)

- Each person explain their project idea and data they will use
- Questions about data, how to get
- Work through process of downloading, organizing data in Excel Power Query Editor 
