---
title: "Lecture 14.2"
subtitle: "The Rise of Nationlism and Socialism(?)"
author: "Emmanuel Teitelbaum"
footer: "[PSC 2339 Website](https://psc2339.com)"
logo: "images/cpe_logo.png"
format:
  revealjs:
    theme: moon
    transition: fade
    slide-number: true
execute:
  echo: false
  freeze: auto
---

# Populism in Europe

## Golden Years of Post-War Capitalism

- Trade $\rightarrow$ growth $\rightarrow$ social safety net, wage gains & social peace
- Low unemployment, low inflation
- Came to an end in 1970s for same reasons in the U.S.
	- Overcapacity 
	- Regulations 
	- Aggressive unions (in some countries, but not all)
	- Higher oil prices (energy crisis)

## Crisis and Fallout {.smaller}

- Deficit spending that stimulated demand in golden years made things worse in the crisis
	- Increased inflation
	- Undermined investment 
	- Increased demand for imports, worsening BOP
- To cope with the crisis, leaders turned away from Keynesian policies and toward neoliberal policies
	- Tried to limit wage increases
	- Raised taxes to tamp down consumer demand
	- Raised interest rates 
	- Squashed or coopted unions
	- Removed regulations on industry
	- Lowered taxes on businesses and the wealthy
	- Etc. 

## Immigration 

- During the boom years, labor was in short supply, immigrants came for work

- In the 1980s, however, new immigrants were asylum seekers

- Most recent wave of refugees is from refugees trying to escape the violence in the Middle East 

- [cool map](https://www.lucify.com/the-flow-towards-europe/) 

## The European Union 1 {.smaller}

- Precursors to the EU (1950s)
	- European Coal and Steel Community
	- European Economic Community 
	- France, West Germany, Netherlands, Luxembourg, Belgium and Italy
- Formation of EU in 1993
	- Allowed goods and people to move freely
	- Original six plus Greece, Spain, Portugal, the UK, Ireland and Denmark
	- All except UK and Denmark also signed onto the Euro in 1999

## The Europe Union 2 {.smaller}

- Stability and Growth Pact (1997)
	- Members' deficits had to stay below 3% of GDP and debt below 60% of GDP
	- Severely constrained government spending
	- Devaluations impossible and tariffs forbidden
	- Cemented in place neoliberal policy, no room for Keynesian response to downturns
- Freedom of movement
	- Unions opposed because companies could move to places with cheaper labor
	- Right opposed because of influx of immigrants from poorer EU countries

# Judis Discussion

## Discussion Strategy

- Identify one chapter from Part II or Part III from Judis
- Meet with other people who read chapter from same part of book
- Now share findings with a group that read a chapter from different part
- Question: should the U.S. abandon globalism? 

# Project Discussion

- Meet in same groups as last class
- Make sure everyone can use the Excel Power Query Editor
- Have you downloaded your data? 
- Is it ready for Power BI? 
- Where are you stuck? 


