---
title: "Project Assignment 1"
subtitle: "Outline and Sources"
editor: visual
---

## Overview

The purpose of this assignment is to come up with a plan for your final
project. The final project is going to involve creating a report in
Microsoft Power BI. If you can find the link to the online Power BI app
[here](https://myapps.microsoft.com). And if you are a Microsoft Windows
user, you can download the desktop version for free
[here](https://powerbi.microsoft.com/en-us/desktop/).

For the next few weeks you are going to work with me and your classmates
to come up with a proposed plan for your report. You will first write an
outline of your plan (this assignment) and then write a white paper that
will flesh out the details.

The topic of your white paper and the Tableau dashboard should be
related to of the topics that we cover during the course (democracy and
development, women's empowerment, clientelism, the welfare state, etc.).
So the first thing to do is to have a look at the syllabus and see what
topic most appeals to you.

## Steps

1)  Choose a topic
2)  Find a [dataset](/project/project-datasets.html) to work with
3)  Gather sources relevant to your topic and generate a preliminary
    bibliography.
4)  Write an outline for a [white
    paper](https://www.instructionalsolutions.com/blog/how-to-write-white-paper)
    describing the need for and purpose of your Power BI report

## What to Submit

You will submit a one-page outline along with a preliminary
bibliography. Your outline will consist of the following parts:

1)  A 100 word abstract outlining the importance of your topic and the
    need for further analysis of it.
2)  A statement of the specific problem to be addressed by your research
    and analysis.
3)  Background information regarding the problem that you have
    identified.
4)  The proposed analysis, which should consist of two elements:
    1.  a description of the data you will analyze; and
    2.  a description the visualizations you plan to include.

For the dataset, be sure to identify one that is complete and includes
both a *cross-sectional* as well as a *time series* component, e.g. data
that spans across countries or regions and time.

For the visualizations, you should describe at least four: a bar chart,
a line chart, a scatter plot and a map. You don't have to do the
visualizations yet, but be specific in terms of what your plan is for
them.

Your outline can be in the form of short paragraphs or bullet points.
