---
title: "Data Assignment 1"
subtitle: "Working With Data in Excel"
editor: visual
---

## Overview

The purpose of this exercise is to teach you about cell references and
basic functions in Microsoft Excel. You will find the assigned units in
Dataquest and [this video](https://www.youtube.com/watch?v=jSl9rydcd7k)
helpful in completing it.

## Steps

1.  Go to Gapminder's [data download](https://www.gapminder.org/data/)
    page.
2.  Select an indicator that you want to work with and download the
    Excel file. You can choose any indicator besides life expectancy
    (which was used in the instructional video).
3.  After opening the file in Excel, have a look at the data. Make sure
    that there are not too many observations and that the file includes
    numbers and not text, e.g. "1,000,000" as opposed to "1M." If there
    are problems with the data, try a different indicator. Make sure
    that there are years across the top row and country names in the
    columns. Think about what units the data are in., e.g. thousands of
    dollars, millions of people, etc. so that you have a sense of what
    you are working with. Look for some basic trends and patterns in the
    data and see if they make sense to you.
4.  If the data look good, create a new worksheet. Name it something
    like "analysis."
5.  In the new worksheet, choose four years to analyze that are roughly
    evenly spaced across the time period covered by the data. Follow the
    example in the video to calculate the following values: minimum,
    median, mean, and maximum. Next, choose a value that seems like an
    interesting threshold to explore. Count the number and percentage of
    countries above above that threshold. Put the information in a table
    like this:

|            | Year $X$ | Year $Y$ | Year $Z$ | Year $Q$ |
|------------|----------|----------|----------|----------|
| Minimum    |          |          |          |          |
| Median     |          |          |          |          |
| Mean       |          |          |          |          |
| Maximum    |          |          |          |          |
| No. \> $x$ |          |          |          |          |
| \% \> $x$  |          |          |          |          |

6.  Identify an interesting twenty-year period to analyze Take averages
    of the value of your indicator over this period and place them in a
    separate row.
7.  Save your workbook.
8.  Upload your workbook to
    [Blackboard](https://blackboard.gwu.edu/webapps/blackboard/content/listContentEditable.jsp?content_id=_12226807_1&course_id=_374099_1&mode=reset).
