---
title: "Data Assignment 2"
subtitle: "Creating Visualizations in Excel"
editor: visual
---

## Overview

The purpose of this assignment is for you to learn how to produce data
visualizations in Excel. You will find the assigned modules in Dataquest
and the following videos helpful in completing it: [bar
chart](https://www.youtube.com/watch?v=G9vKgrtDZ-w&t=21s); [line
chart](https://www.youtube.com/watch?v=YOpwcihO-iY&t=66s); [scatter
plot](https://www.youtube.com/watch?v=NDszBjbvSFA&t=29s); and a
[map](https://www.youtube.com/watch?v=ixjWeXbYVl0&t=98s).

## Steps

1.  Go to the World Bank's [World Development Indicators
    Database](https://databank.worldbank.org/source/world-development-indicators).
2.  Choose an indicator that you want to work with. It can anything but
    female labor force participation but it should be an indicator with
    a good amount of coverage, meaning that the data are available for
    most countries and years.
3.  Select a group of four or five countries to compare and create a bar
    chart. Follow the steps in the bar chart video to create a bar chart
    comparing those countries. Save your file.
4.  Using those same countries, follow the steps in the line chart video
    to create a line chart for your countries. Save the file with your
    newly created line chart.
5.  Now select all countries and one other indicator to compare your
    indicator with. This should be something that you think is related
    to your indicator, e.g. would display a positive or negative
    correlation with your indicator. Follow the steps in the scatter
    plot video to create a scatter plot for your indicator and the other
    variable you have chosen. Save your file with the new scatter plot
    visualization.
6.  Now follow the steps in the map video to create a map visualization
    for your indicator. Save the file with the visualization.
7.  Copy the four visualizations that you have made from the Excel files
    and paste them into a Word file. Make sure that each visualization
    has an appropriate title. Now below each visualization include a
    source note and write a line or two describing what you see in the
    visualization (e.g. trends, comparisons relationshsips).
8.  Save the Word file and upload it to
    [Blackboard](https://blackboard.gwu.edu/webapps/blackboard/content/listContentEditable.jsp?content_id=_12226807_1&course_id=_374099_1).
